spring.application.name=api
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
aws.region=us-east-2
aws.bucket.cars-images=${AWS_BUCKET_CARS_IMAGES}
aws.bucket.cars-models3d=${AWS_BUCKET_CARS_MODELS3D}
spring.servlet.multipart.max-file-size=80MB
spring.servlet.multipart.max-request-size=80MB
server.port=${PORT:8080}
api.security.token.secret=${JWT_SECRET}
scheduler.reservation.cron=${RESERVATION_SCHEDULER_CRON}