spring.application.name=api
spring.datasource.url=jdbc:postgresql://db.jmssfgyesjnlygyxelgd.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
aws.region=us-east-2
aws.bucket.name=luxmotors-carros-imagens
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

