spring.application.name=api
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
aws.region=us-east-2
aws.bucket.name=luxmotors-carros-imagens
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.port=${PORT:8080}
api.security.token.secret=${JWT_SECRET}

